"""Module containing constants for the model card schema and related mappings."""  # noqa: E501

SCHEMA = {
    "card_metadata": {
        "card_creation_date": {},
        "version_number": {},
        "version_changes": {},
        "doi": {},
    },
    "model_basic_information": {
        "name": {},
        "creation_date": {},
        "version_number": {},
        "version_changes": {},
        "doi": {},
        "model_scope_summary": {},
        "model_scope_anatomical_site": {},
        "clearance_type": {},
        "clearance_approved_by_name": {},
        "clearance_approved_by_institution": {},
        "clearance_approved_by_contact_email": {},
        "clearance_additional_information": {},
        "intended_users": {},
        "observed_limitations": {},
        "potential_limitations": {},
        "type_of_learning_architecture": {},
        "developed_by_name": {},
        "developed_by_institution": {},
        "developed_by_email": {},
        "conflict_of_interest": {},
        "software_license": {},
        "code_source": {},
        "model_source": {},
        "citation_details": {},
        "url_info": {},
    },
    "technical_specifications": {
        "model_pipeline_summary": {},
        "model_pipeline_figure_appendix_note": {},
        "model_inputs": {},
        "model_outputs": {},
        "pre_processing": {},
        "post_processing": {},
    },
    "hw_and_sw": {
        "libraries_and_dependencies": {},
        "hardware_recommended": {},
        "inference_time_for_recommended_hw": {},
        "installation_getting_started": {},
        "environmental_impact": {},
    },
    "training_data": {
        "model_name": {},
        "url_doi_to_model_card": {},
        "tuning_technique": {},
        "total_size": {},
        "number_of_patients": {},
        "source": {},
        "acquisition_period": {},
        "inclusion_exclusion_criteria": {},
        "type_of_data_augmentation": {},
        "strategy_for_data_augmentation": {},
        "url_info": {},
        "treatment_modality_train": {"model_types": ["Dose prediction"]},
        "beam_configuration_energy": {"model_types": ["Dose prediction"]},
        "dose_engine": {"model_types": ["Dose prediction"]},
        "target_volumes_and_prescription": {
            "model_types": ["Dose prediction"],
        },
        "number_of_fractions": {"model_types": ["Dose prediction"]},
        "reference_standard": {},
        "reference_standard_qa": {},
        "reference_standard_qa_additional_information": {},
        "icd10_11": {},
        "tnm_staging": {},
        "age": {},
        "sex": {},
        "target_volume_cm3": {},
        "bmi": {},
        "additional_patient_info": {},
        "validation_strategy": {},
        "validation_data_partition": {},
        "weights_initialization": {},
        "epochs": {},
        "optimiser": {},
        "learning_rate": {},
        "train_and_validation_loss_curves_appendix_note": {},
        "model_choice_criteria": {},
        "inference_method": {},
    },
    "evaluation_data": {
        "evaluation_date": {},
        "evaluated_same_as_approved": {},
        "evaluated_by_name": {},
        "evaluated_by_institution": {},
        "evaluated_by_contact_email": {},
        "evaluation_frame": {},
        "sanity_check": {"model_types": ["Image-to-Image translation"]},
        "total_size": {},
        "number_of_patients": {},
        "source": {},
        "acquisition_period": {},
        "inclusion_exclusion_criteria": {},
        "url_info": {},
        "treatment_modality_eval": {"model_types": ["Dose prediction"]},
        "beam_configuration_energy": {"model_types": ["Dose prediction"]},
        "dose_engine": {"model_types": ["Dose prediction"]},
        "target_volumes_and_prescription": {
            "model_types": ["Dose prediction"],
        },
        "number_of_fractions": {"model_types": ["Dose prediction"]},
        "reference_standard": {},
        "reference_standard_qa": {},
        "reference_standard_qa_additional_information": {},
        "icd10_11_ev": {},
        "tnm_staging_ev": {},
        "age_ev": {},
        "sex_ev": {},
        "target_volume_cm3_ev": {},
        "bmi_ev": {},
        "additional_patient_info_ev": {},
        "uncertainty_metrics_method": {},
        "uncertainty_metrics_results": {},
        "other_method": {},
        "other_results": {},
        "evaluators_information": {},
        "likert_scoring_method": {},
        "likert_scoring_results": {},
        "turing_test_method": {},
        "turing_test_results": {},
        "time_saving_method": {},
        "time_saving_results": {},
        "qualitative_other_method": {},
        "qualitative_other_results": {},
        "explainability": {},
        "citation_details": {},
    },
    "other_considerations": {
        "responsible_use_and_ethical_considerations": {},
        "risk_analysis": {},
        "post_market_surveillance_live_monitoring": {},
    },
}

LEARNING_ARCHITECTURE = {
    "total_number_trainable_parameters": "",
    "number_of_inputs": "",
    "input_content_list": [],
    "additional_information_input_content": "",
    "input_format": "",
    "input_size": "",
    "number_of_outputs": "",
    "output_content_list": [],
    "additional_information_output_content": "",
    "output_format": "",
    "output_size": "",
    "loss_function": "",
    "batch_size": "",
    "regularisation": "",
    "architecture_figure_appendix_note": "",
    "uncertainty_quantification_techniques": "",
    "explainability_techniques": "",
    "additional_information_ts": "",
    "citation_details_ts": "",
}

DATA_INPUT_OUTPUT_TS = {
    "image_resolution": "Image resolution",
    "patient_positioning": "Patient positioning",
    "scanner_model": "Scan(s) manufacturer and model",
    "scan_acquisition_parameters": "Scan acquisition parameters",
    "scan_reconstruction_parameters": "Scan reconstruction parameters",
    "fov": "FOV",
}

EVALUATION_METRIC_FIELDS = {
    "type_ism": [
        "on_volume_ism",
        "registration_ism",
        "sample_data_ism",
        "mean_data_ism",
        "figure_ism_appendix_note",
    ],
    "type_dose_dm": [
        "metric_specifications_dm",
        "on_volume_dm",
        "registration_dm",
        "treatment_modality_dm",
        "dose_engine_dm",
        "dose_grid_resolution_dm",
        "tps_vendor_dm",
        "sample_data_dm",
        "mean_data_dm",
        "figure_dm_appendix_note",
    ],
    "type_gm_seg": [
        "metric_specifications_gm_seg",
        "on_volume_gm_seg",
        "sample_data_gm_seg",
        "mean_data_gm_seg",
        "figure_gm_seg_appendix_note",
    ],
    "type_dose_dm_seg": [
        "metric_specifications_dm_seg",
        "on_volume_dm_seg",
        "treatment_modality_dm_seg",
        "dose_engine_dm_seg",
        "dose_grid_resolution_dm_segtps_vendor_dm_seg",
        "sample_data_dm_seg",
        "mean_data_dm_seg",
        "figure_dm_seg_appendix_note",
    ],
    "type_dose_dm_dp": [
        "metric_specifications_dm_dp",
        "on_volume_dm_dp",
        "dose_grid_resolution_dm_dp",
        "sample_data_dm_dp",
        "mean_data_dm_dp",
        "figure_dm_dp_appendix_note",
    ],
    "type_metrics_other": [
        "additional_info_other",
        "sample_data_other",
        "mean_data_other",
        "figure_other_appendix_note",
    ],
}
TASK_METRIC_MAP = {
    "Image-to-Image translation": ["type_ism", "type_dose_dm"],
    "Segmentation": ["type_gm_seg", "type_dose_dm_seg"],
    "Dose prediction": ["type_dose_dm_dp"],
    "Other": ["type_metrics_other"],
}
