"""add_publication_workflow

Revision ID: dfd4d38319af
Revises: db394051b523
Create Date: 2026-03-22 17:49:06.366871+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfd4d38319af'
down_revision: Union[str, None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_card', sa.Column('publication_status', sa.String(length=20), server_default='draft', nullable=False))
    op.add_column('model_card', sa.Column('owner_id', sa.Uuid(native_uuid=False), nullable=True))
    op.create_index(op.f('ix_model_card_owner_id'), 'model_card', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'model_card', 'user', ['owner_id'], ['id'], ondelete='SET NULL')
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    op.drop_constraint(None, 'model_card', type_='foreignkey')
    op.drop_index(op.f('ix_model_card_owner_id'), table_name='model_card')
    op.drop_column('model_card', 'owner_id')
    op.drop_column('model_card', 'publication_status')
    # ### end Alembic commands ###
